PFD Project/Controllers/FingerprintController.cs
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using PFD_Project.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rsk.AspNetCore.Fido;
using Rsk.AspNetCore.Fido.Dtos;

namespace PFD_Project.Controllers
{
    public class FingerprintController : Controller
    {
        private readonly IFidoAuthentication fido;

        public FingerprintController(IFidoAuthentication fido)
        {
            this.fido = fido ?? throw new ArgumentNullException(nameof(fido));
        }

        public IActionResult Index() => View();

        [Authorize]
        public IActionResult Secure() => View("Index");

        public IActionResult StartRegistration() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegistrationModel model)
        {
            var challenge = await fido.InitiateRegistration(model.UserId, model.DeviceName);

            return View(challenge.ToBase64Dto());
        }

        [HttpPost]
        public async Task<IActionResult> CompleteRegistration([FromBody] Base64FidoRegistrationResponse registrationResponse)
        {
            var result = await fido.CompleteRegistration(registrationResponse.ToFidoResponse());

            if (result.IsError) return BadRequest(result.ErrorDescription);
            return Ok();
        }

        public ActionResult StartLogin()
        {
            string accountNo = HttpContext.Session.GetString("AccountNo");
            LoginModel user1 = new LoginModel();
            if (accountNo != null)
            {
                user1.UserId = accountNo;
            }
            return View(user1);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginModel model)
        {
            var challenge = await fido.InitiateAuthentication(model.UserId);

            return View(challenge.ToBase64Dto());
        }

        [HttpPost]
        public async Task<IActionResult> CompleteLogin([FromBody] Base64FidoAuthenticationResponse authenticationResponse)
        {
            var result = await fido.CompleteAuthentication(authenticationResponse.ToFidoResponse());

            if (result.IsSuccess)
            {
                await HttpContext.SignInAsync("cookie", new ClaimsPrincipal(new ClaimsIdentity(new List<Claim>
                {
                    new Claim("sub", result.UserId)
                }, "cookie")));
            }

            if (result.IsError) return BadRequest(result.ErrorDescription);
            return Ok();
        }
    }
}

PFD Project/Views/Fingerprint/Index.cshtml
@using System.Security.Claims
@{
    ViewData["Title"] = "Home Page";
}


@if (User.Identity.IsAuthenticated)
{
    <h1>Authenticated!</h1>
    <p>
        Hello, @User.FindFirstValue("sub")
    </p>
}
else
{
    <h1>Unauthenticated</h1>
}

<ul class="navbar-nav flex-grow-1">
	<li class="nav-item">
		<a class="nav-link text-dark" asp-area="" asp-controller="Fingerprint" asp-action="Index">Home</a>
	</li>
	<li class="nav-item">
		<a class="nav-link text-dark" asp-area="" asp-controller="Fingerprint" asp-action="StartRegistration">Register</a>
	</li>
	<li class="nav-item">
		<a class="nav-link text-dark" asp-area="" asp-controller="Fingerprint" asp-action="Secure">Login</a>
	</li>
</ul>

PFD Project/Views/Fingerprint/Login.cshtml
@using Newtonsoft.Json
@model Rsk.AspNetCore.Fido.Dtos.Base64FidoAuthenticationChallenge

<h2>Please use your authenticator</h2>

<script>
    // Challenge
    let challengeBytesAsString = atob("@Html.Raw(Model.Base64Challenge)");
    let challenge = new Uint8Array(challengeBytesAsString.length);
    for (let i = 0; i < challengeBytesAsString.length; i++) {
        challenge[i] = challengeBytesAsString.charCodeAt(i);
    }

    // RP ID
    let rpId = "@Model.RelyingPartyId";

    // Allowed credentials
    let keys = JSON.parse('@Html.Raw(JsonConvert.SerializeObject(Model.Base64KeyIds))');
    let allowCredentials = [];

    for (let i = 0; i < keys.length; i++) {
        let keyIdBytesAsString = window.atob(keys[i]);

        let key = new Uint8Array(keyIdBytesAsString.length);
        for (let i = 0; i < keyIdBytesAsString.length; i++) {
            key[i] = keyIdBytesAsString.charCodeAt(i);
        }

        allowCredentials.push({
            type: "public-key",
            id: key
        });
    }

    navigator.credentials.get({ publicKey: { challenge, rpId, allowCredentials } })
        .then((result) => {

            // base64 encode array buffers
            let encodedResult = {
                id: result.id,
                rawId: btoa(String.fromCharCode.apply(null, new Uint8Array(result.rawId))),
                type: result.type,
                response: {
                    authenticatorData:
                        btoa(String.fromCharCode.apply(null, new Uint8Array(result.response.authenticatorData))),
                    signature:
                        btoa(String.fromCharCode.apply(null, new Uint8Array(result.response.signature))),
                    userHandle:
                        btoa(String.fromCharCode.apply(null, new Uint8Array(result.response.userHandle))),
                    clientDataJSON:
                        btoa(String.fromCharCode.apply(null, new Uint8Array(result.response.clientDataJSON)))
                }
            };

            // post to login callback endpoint and redirect to homepage
            $.ajax({
                url: '/Fingerprint/CompleteLogin',
                type: 'POST',
                contentType: 'application/json',
                data: JSON.stringify(encodedResult),
                success: function () {
                    window.location.href = "/Home/Home";
                }
            });
        })
        .catch((error) => {
            console.error(error);
        });
</script>

PFD Project/Views/Fingerprint/Register.cshtml
@model Rsk.AspNetCore.Fido.Dtos.Base64FidoRegistrationChallenge

<h2>Please use your authenticator</h2>

<script>
    // Challenge
    let challengeBytesAsString = atob("@Html.Raw(Model.Base64Challenge)");
    let challenge = new Uint8Array(challengeBytesAsString.length);
    for (let i = 0; i < challengeBytesAsString.length; i++) {
        challenge[i] = challengeBytesAsString.charCodeAt(i);
    }

    // Supported algorithms, ordered by preference
    var pubKeyCredParams = [
        {
            type: "public-key",
            alg: -8
        },
        {
            type: "public-key",
            alg: -259
        },
        {
            type: "public-key",
            alg: -39
        },
        {
            type: "public-key",
            alg: -36
        },
        {
            type: "public-key",
            alg: -258
        },
        {
            type: "public-key",
            alg: -38
        },
        {
            type: "public-key",
            alg: -35
        },
        {
            type: "public-key",
            alg: -7
        },
        {
            type: "public-key",
            alg: -257
        },
        {
            type: "public-key",
            alg: -37
        },
        {
            type: "public-key",
            alg: -7
        },
        {
            type: "public-key",
            alg: -65535
        }
    ];

    // Relying party details
    let rp = {
        id: "@Model.RelyingPartyId",
        name: "RSK FIDO Quickstart - Core"
    };

    // User handle
    let userHandleBytesAsString = atob("@Html.Raw(Model.Base64UserHandle)");
    let userHandle = new Uint8Array(userHandleBytesAsString.length);
    for (let i = 0; i < userHandleBytesAsString.length; i++) {
        userHandle[i] = userHandleBytesAsString.charCodeAt(i);
    }

    let user = {
        name: "@Model.UserId",
        displayName: "@Model.UserId",
        id: userHandle
    };

    navigator.credentials.create({ publicKey: { challenge, rp, user, pubKeyCredParams } })
        .then((credentials) => {

            // base64 encode array buffers
            let encodedCredentials = {
                id: credentials.id,
                rawId: btoa(String.fromCharCode.apply(null, new Uint8Array(credentials.rawId))),
                type: credentials.type,
                response: {
                    attestationObject:
                        btoa(String.fromCharCode.apply(null, new Uint8Array(credentials.response.attestationObject))),
                    clientDataJSON:
                        btoa(String.fromCharCode.apply(null, new Uint8Array(credentials.response.clientDataJSON)))
                }
            };

            // post to register callback endpoint and redirect to homepage
            $.ajax({
                url: '/Fingerprint/CompleteRegistration',
                type: 'POST',
                contentType: 'application/json',
                data: JSON.stringify(encodedCredentials),
                success: function () {
                    window.location.href = "/";
                },
                error: function () {
                    console.error("Error from server...");
                }
            });
        })
        .catch((error) => {
            console.error(error);
        });
</script>

PFD Project/Views/Fingerprint/StartLogin.cshtml
@model PFD_Project.Models.LoginModel

<h2>Login</h2>
<form asp-action="Login">
    <div class="form-group">
        <label asp-for="UserId"></label>
        <input asp-for="UserId" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

PFD Project/Views/Fingerprint/StartRegistration.cshtml
@model PFD_Project.Models.RegistrationModel

<h2>Register</h2>
<form asp-action="Register">
    <div class="form-group">
        <label asp-for="UserId"></label>
        <input asp-for="UserId" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="DeviceName"></label>
        <input asp-for="DeviceName" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>